from typing import Any, Dict, List, Optional


class Reply:
    def say(self, text: str) -> None: ...
    def ask(self, prompt: str) -> None: ...
    def summarize(self, slots: Dict[str, Any]) -> None: ...
    def ticket_done(self, ticket: Dict[str, Any]) -> None: ...
    def show_route(self, route: Dict[str, Any]) -> None: ...
    def show_checklist(self, info: Dict[str, Any]) -> None: ...
    def show_triage_suggestions(self, suggestions: Optional[Any]) -> None: ...
    def smalltalk(self) -> None: ...
    def suggest(self, items: List[str]) -> None: ...


class Metrics:
    def bump(self, key: str) -> None: ...
    def mark_session_start(self) -> None: ...
    def mark_session_end(self) -> None: ...


class QueueService:
    def create_ticket(self, slots: Dict[str, Any]) -> Dict[str, Any]: ...


class MapService:
    def get_route(self, slots: Dict[str, Any]) -> Dict[str, Any]: ...


class KBService:
    def query(self, slots: Dict[str, Any]) -> Any: ...


class HandoffService:
    def open_channel(self) -> None: ...
    def close_channel(self) -> None: ...


class SessionService:
    def init(self) -> None: ...
    def close(self) -> None: ...

