from __future__ import annotations

from typing import Any, Dict, Tuple

# Centralised catalogue of end-user symptoms recognised by the NLU triage pipeline.
# The hints contain every-day phrasing so that keyword spotting from normalized text
# remains simple while triage logic downstream can operate on canonical IDs.
TRIAGE_SYMPTOM_RULES: Tuple[Dict[str, Any], ...] = (
    {
        "symptom_id": "general_checkup",
        "symptom_name": "Triệu chứng chung",
        "base_confidence": 0.65,
        "hints": (
            "kiểm tra sức khỏe",
            "khám tổng quát",
            "thăm khám tổng quát",
            "khám ban đầu",
            "general checkup",
        ),
    },
    {
        "symptom_id": "body_ache",
        "symptom_name": "Đau mỏi toàn thân",
        "base_confidence": 0.65,
        "hints": (
            "đau toàn thân",
            "nhức mỏi",
            "mệt mỏi",
            "mỏi người",
            "body ache",
            "fatigue",
        ),
    },
    {
        "symptom_id": "chest_pain",
        "symptom_name": "Đau ngực, tức ngực",
        "base_confidence": 0.7,
        "hints": (
            "đau ngực",
            "tức ngực",
            "thắt ngực",
            "đau vùng ngực",
            "ngực đau",
            "ngực tức",
            "chest pain",
            "tightness chest",
        ),
    },
    {
        "symptom_id": "palpitations",
        "symptom_name": "Tim đập nhanh, hồi hộp",
        "base_confidence": 0.65,
        "hints": (
            "hồi hộp",
            "tim đập nhanh",
            "loạn nhịp",
            "đập thình thịch",
            "palpitation",
            "heart racing",
        ),
    },
    {
        "symptom_id": "shortness_of_breath",
        "symptom_name": "Khó thở, thở gấp",
        "base_confidence": 0.7,
        "hints": (
            "khó thở",
            "thở gấp",
            "thở khò khè",
            "thở hụt hơi",
            "thở không đủ",
            "không thở nổi",
            "shortness of breath",
            "difficulty breathing",
            "hard to breathe",
        ),
    },
    {
        "symptom_id": "wheezing",
        "symptom_name": "Khò khè, thở rít",
        "base_confidence": 0.65,
        "hints": (
            "khò khè",
            "thở rít",
            "khò rít",
            "co thắt phế quản",
            "wheezing",
        ),
    },
    {
        "symptom_id": "chronic_cough",
        "symptom_name": "Ho kéo dài",
        "base_confidence": 0.65,
        "hints": (
            "ho kéo dài",
            "ho dai dẳng",
            "ho lâu",
            "ho có đờm",
            "ho nhiều tuần",
            "ho mãn tính",
            "chronic cough",
        ),
    },
    {
        "symptom_id": "acute_cough",
        "symptom_name": "Ho nhiều, ho dữ dội",
        "base_confidence": 0.65,
        "hints": (
            "ho nhiều",
            "ho liên tục",
            "ho khan",
            "ho đờm",
            "ho dữ dội",
            "coughing",
            "cough",
        ),
    },
    {
        "symptom_id": "hemoptysis",
        "symptom_name": "Ho ra máu",
        "base_confidence": 0.7,
        "hints": (
            "ho ra máu",
            "khạc ra máu",
            "coughing blood",
        ),
    },
    {
        "symptom_id": "fever",
        "symptom_name": "Sốt",
        "base_confidence": 0.65,
        "hints": (
            "sốt",
            "nóng sốt",
            "sốt nhẹ",
            "fever",
            "feverish",
        ),
    },
    {
        "symptom_id": "high_fever",
        "symptom_name": "Sốt cao",
        "base_confidence": 0.7,
        "hints": (
            "sốt cao",
            "sốt 39",
            "sốt 40",
            "sốt rất cao",
            "high fever",
        ),
    },
    {
        "symptom_id": "chills",
        "symptom_name": "Rét run, ớn lạnh",
        "base_confidence": 0.65,
        "hints": (
            "rét run",
            "ớn lạnh",
            "run cầm cập",
            "chills",
            "shivering",
        ),
    },
    {
        "symptom_id": "cold_sweat",
        "symptom_name": "Vã mồ hôi lạnh",
        "base_confidence": 0.6,
        "hints": (
            "mồ hôi lạnh",
            "vã mồ hôi lạnh",
            "đổ mồ hôi lạnh",
            "cold sweat",
        ),
    },
    {
        "symptom_id": "skin_rash",
        "symptom_name": "Phát ban, nổi mẩn",
        "base_confidence": 0.7,
        "hints": (
            "phát ban",
            "nổi mẩn",
            "nổi mề đay",
            "mụn nước",
            "rash",
            "hives",
        ),
    },
    {
        "symptom_id": "skin_itching",
        "symptom_name": "Ngứa hoặc khô da",
        "base_confidence": 0.65,
        "hints": (
            "ngứa da",
            "khô da",
            "tróc vảy",
            "gãi nhiều",
            "itching",
            "pruritus",
        ),
    },
    {
        "symptom_id": "runny_nose",
        "symptom_name": "Chảy mũi, nghẹt mũi",
        "base_confidence": 0.65,
        "hints": (
            "chảy mũi",
            "sổ mũi",
            "nghẹt mũi",
            "tịt mũi",
            "runny nose",
            "stuffy nose",
        ),
    },
    {
        "symptom_id": "sore_throat",
        "symptom_name": "Đau họng, khàn tiếng",
        "base_confidence": 0.65,
        "hints": (
            "đau họng",
            "rát họng",
            "khó nuốt",
            "khàn tiếng",
            "mất tiếng",
            "sore throat",
        ),
    },
    {
        "symptom_id": "ear_pain",
        "symptom_name": "Đau tai, ù tai",
        "base_confidence": 0.65,
        "hints": (
            "đau tai",
            "ù tai",
            "viêm tai",
            "tai đau",
            "ear pain",
            "earache",
        ),
    },
    {
        "symptom_id": "eye_pain",
        "symptom_name": "Đau, cộm xốn mắt",
        "base_confidence": 0.65,
        "hints": (
            "đau mắt",
            "cộm mắt",
            "ngứa mắt",
            "mắt khó chịu",
            "eye pain",
        ),
    },
    {
        "symptom_id": "red_eye",
        "symptom_name": "Mắt đỏ, viêm kết mạc",
        "base_confidence": 0.65,
        "hints": (
            "đau mắt đỏ",
            "mắt đỏ",
            "viêm kết mạc",
            "red eye",
            "pink eye",
        ),
    },
    {
        "symptom_id": "blurred_vision",
        "symptom_name": "Mờ mắt, nhìn kém",
        "base_confidence": 0.65,
        "hints": (
            "mờ mắt",
            "nhìn kém",
            "mắt mờ",
            "nhìn không rõ",
            "blurred vision",
        ),
    },
    {
        "symptom_id": "vision_loss",
        "symptom_name": "Giảm thị lực, mất thị lực",
        "base_confidence": 0.7,
        "hints": (
            "mất thị lực",
            "mất nhìn",
            "nhìn không thấy",
            "giảm thị lực đột ngột",
            "vision loss",
            "loss of vision",
        ),
    },
    {
        "symptom_id": "watery_eye",
        "symptom_name": "Chảy nước mắt, chói sáng",
        "base_confidence": 0.6,
        "hints": (
            "chảy nước mắt",
            "chói sáng",
            "nhạy cảm ánh sáng",
            "watery eyes",
        ),
    },
    {
        "symptom_id": "abdominal_pain",
        "symptom_name": "Đau bụng, đầy hơi",
        "base_confidence": 0.65,
        "hints": (
            "đau bụng",
            "đau dạ dày",
            "đầy bụng",
            "đau thượng vị",
            "stomachache",
            "abdominal pain",
        ),
    },
    {
        "symptom_id": "abdominal_pain_ruq",
        "symptom_name": "Đau hạ sườn phải",
        "base_confidence": 0.65,
        "hints": (
            "đau hạ sườn phải",
            "đau gan",
            "đau cạnh sườn phải",
            "đau túi mật",
            "right upper abdominal pain",
        ),
    },
    {
        "symptom_id": "abdominal_pain_mid",
        "symptom_name": "Đau bụng quanh rốn",
        "base_confidence": 0.65,
        "hints": (
            "đau quanh rốn",
            "đau giữa bụng",
            "đau bụng giữa",
            "đau bụng quặn",
            "mid abdominal pain",
        ),
    },
    {
        "symptom_id": "abdominal_pain_lower",
        "symptom_name": "Đau bụng dưới",
        "base_confidence": 0.65,
        "hints": (
            "đau bụng dưới",
            "đau bụng dưới rốn",
            "đau bụng âm ỉ",
            "đau vùng chậu",
            "lower abdominal pain",
        ),
    },
    {
        "symptom_id": "nausea",
        "symptom_name": "Buồn nôn, nôn ói",
        "base_confidence": 0.65,
        "hints": (
            "buồn nôn",
            "nôn ói",
            "ói mửa",
            "ói liên tục",
            "vomit",
            "nausea",
        ),
    },
    {
        "symptom_id": "digestive_disorder",
        "symptom_name": "Rối loạn tiêu hóa",
        "base_confidence": 0.6,
        "hints": (
            "rối loạn tiêu hóa",
            "đầy bụng",
            "khó tiêu",
            "ợ hơi",
            "ợ nóng",
            "digestive disorder",
        ),
    },
    {
        "symptom_id": "diarrhea",
        "symptom_name": "Tiêu chảy",
        "base_confidence": 0.65,
        "hints": (
            "tiêu chảy",
            "đi ngoài nhiều lần",
            "phân lỏng",
            "chạy bụng",
            "diarrhea",
        ),
    },
    {
        "symptom_id": "vomiting_blood",
        "symptom_name": "Nôn ra máu",
        "base_confidence": 0.7,
        "hints": (
            "nôn ra máu",
            "ói ra máu",
            "hematemesis",
            "vomiting blood",
        ),
    },
    {
        "symptom_id": "black_stool",
        "symptom_name": "Đi ngoài phân đen",
        "base_confidence": 0.7,
        "hints": (
            "phân đen",
            "đi ngoài phân đen",
            "đi tiêu phân đen",
            "melena",
            "black stool",
        ),
    },
    {
        "symptom_id": "epigastric_burning",
        "symptom_name": "Nóng rát thượng vị",
        "base_confidence": 0.65,
        "hints": (
            "nóng rát thượng vị",
            "cồn cào thượng vị",
            "đau dạ dày",
            "burning stomach",
            "epigastric burning",
        ),
    },
    {
        "symptom_id": "painful_urination",
        "symptom_name": "Đái buốt, đái rát",
        "base_confidence": 0.7,
        "hints": (
            "đái buốt",
            "đi tiểu buốt",
            "tiểu đau",
            "đi đái rát",
            "painful urination",
            "dysuria",
        ),
    },
    {
        "symptom_id": "frequent_urination",
        "symptom_name": "Đi tiểu nhiều lần",
        "base_confidence": 0.6,
        "hints": (
            "đi tiểu nhiều",
            "tiểu lắt nhắt",
            "đi tiểu liên tục",
            "tiểu dắt",
            "frequent urination",
        ),
    },
    {
        "symptom_id": "reduced_urination",
        "symptom_name": "Tiểu ít, bí tiểu",
        "base_confidence": 0.65,
        "hints": (
            "tiểu ít",
            "bí tiểu",
            "ít đi tiểu",
            "không đi tiểu được",
            "reduced urination",
            "oliguria",
        ),
    },
    {
        "symptom_id": "swelling_general",
        "symptom_name": "Phù, sưng người",
        "base_confidence": 0.65,
        "hints": (
            "phù nề",
            "sưng chân",
            "sưng tay",
            "sưng mặt",
            "phù toàn thân",
            "edema",
            "swelling",
        ),
    },
    {
        "symptom_id": "numbness",
        "symptom_name": "Tê yếu chi",
        "base_confidence": 0.65,
        "hints": (
            "tê bì",
            "tê tay",
            "tê chân",
            "yếu liệt",
            "liệt nửa người",
            "numbness",
        ),
    },
    {
        "symptom_id": "facial_droop",
        "symptom_name": "Méo miệng, lệch mặt",
        "base_confidence": 0.7,
        "hints": (
            "méo miệng",
            "lệch miệng",
            "mặt xệ",
            "liệt mặt",
            "facial droop",
        ),
    },
    {
        "symptom_id": "speech_difficulty",
        "symptom_name": "Nói khó, nói đớ",
        "base_confidence": 0.7,
        "hints": (
            "nói khó",
            "nói đớ",
            "nói không rõ",
            "nói ngọng đột ngột",
            "speech difficulty",
            "slurred speech",
        ),
    },
    {
        "symptom_id": "headache_severe",
        "symptom_name": "Đau đầu dữ dội",
        "base_confidence": 0.7,
        "hints": (
            "đau đầu dữ dội",
            "đau đầu đột ngột",
            "đau đầu như búa bổ",
            "đau đầu khủng khiếp",
            "severe headache",
            "thunderclap headache",
        ),
    },
    {
        "symptom_id": "dizziness",
        "symptom_name": "Chóng mặt",
        "base_confidence": 0.65,
        "hints": (
            "chóng mặt",
            "choáng váng",
            "hoa mắt",
            "đi loạng choạng",
            "dizziness",
        ),
    },
    {
        "symptom_id": "loss_of_balance",
        "symptom_name": "Mất thăng bằng",
        "base_confidence": 0.65,
        "hints": (
            "mất thăng bằng",
            "đi loạng choạng",
            "không đứng vững",
            "choáng choạng",
            "loss of balance",
        ),
    },
    {
        "symptom_id": "seizure",
        "symptom_name": "Co giật",
        "base_confidence": 0.7,
        "hints": (
            "co giật",
            "giật toàn thân",
            "động kinh",
            "sốc lên cơn",
            "seizure",
            "convulsion",
        ),
    },
    {
        "symptom_id": "loss_of_consciousness",
        "symptom_name": "Ngất, mất ý thức",
        "base_confidence": 0.7,
        "hints": (
            "ngất xỉu",
            "bất tỉnh",
            "mất ý thức",
            "ngất đột ngột",
            "faint",
            "loss of consciousness",
        ),
    },
    {
        "symptom_id": "neck_pain",
        "symptom_name": "Đau cổ, vai gáy",
        "base_confidence": 0.65,
        "hints": (
            "đau cổ",
            "đau vai gáy",
            "cứng cổ",
            "mỏi cổ",
            "đau gáy",
            "neck pain",
        ),
    },
    {
        "symptom_id": "back_pain",
        "symptom_name": "Đau lưng cấp",
        "base_confidence": 0.65,
        "hints": (
            "đau lưng",
            "đau thắt lưng",
            "đau lưng dữ dội",
            "đau lưng cấp",
            "back pain",
        ),
    },
    {
        "symptom_id": "joint_pain",
        "symptom_name": "Đau khớp, sưng khớp",
        "base_confidence": 0.65,
        "hints": (
            "đau khớp",
            "sưng khớp",
            "viêm khớp",
            "cứng khớp",
            "joint pain",
        ),
    },
    {
        "symptom_id": "injury",
        "symptom_name": "Chấn thương",
        "base_confidence": 0.65,
        "hints": (
            "chấn thương",
            "gãy xương",
            "bong gân",
            "trật khớp",
            "té ngã",
            "injury",
            "fracture",
            "sprain",
        ),
    },
    {
        "symptom_id": "burn_injury",
        "symptom_name": "Bỏng",
        "base_confidence": 0.6,
        "hints": (
            "bị bỏng",
            "bỏng nước sôi",
            "bỏng lửa",
            "bỏng điện",
            "bỏng hóa chất",
            "bị phỏng",
            "phỏng nước sôi",
            "phỏng lửa",
            "burn injury",
        ),
    },
    {
        "symptom_id": "open_wound",
        "symptom_name": "Vết thương hở",
        "base_confidence": 0.65,
        "hints": (
            "vết thương hở",
            "vết thương nhiễm trùng",
            "vết thương chảy mủ",
            "vết thương lở loét",
            "open wound",
        ),
    },
    {
        "symptom_id": "skin_blister",
        "symptom_name": "Bóng nước, phỏng rộp",
        "base_confidence": 0.6,
        "hints": (
            "bóng nước",
            "phỏng rộp",
            "mụn nước",
            "blister",
        ),
    },
    {
        "symptom_id": "skin_ulcer",
        "symptom_name": "Loét da, lở loét",
        "base_confidence": 0.6,
        "hints": (
            "lở loét",
            "loét da",
            "vết loét",
            "skin ulcer",
        ),
    },
    {
        "symptom_id": "allergic_reaction",
        "symptom_name": "Dị ứng, nổi mề đay",
        "base_confidence": 0.65,
        "hints": (
            "dị ứng",
            "dị ứng thuốc",
            "dị ứng thức ăn",
            "nổi mề đay",
            "allergic reaction",
            "allergy",
        ),
    },
    {
        "symptom_id": "poisoning",
        "symptom_name": "Ngộ độc",
        "base_confidence": 0.7,
        "hints": (
            "ngộ độc",
            "ngộ độc thức ăn",
            "uống nhầm",
            "trúng độc",
            "poisoning",
        ),
    },
    {
        "symptom_id": "foreign_body_ingestion",
        "symptom_name": "Nuốt dị vật, hóc dị vật",
        "base_confidence": 0.7,
        "hints": (
            "nuốt dị vật",
            "hóc xương",
            "hóc dị vật",
            "trẻ nuốt đồ chơi",
            "ingested foreign body",
            "choking on object",
        ),
    },
    {
        "symptom_id": "child_fever",
        "symptom_name": "Trẻ sốt, ho",
        "base_confidence": 0.65,
        "hints": (
            "trẻ sốt",
            "bé sốt",
            "con sốt",
            "trẻ ho",
            "bé ho",
            "child fever",
        ),
    },
    {
        "symptom_id": "child_poor_appetite",
        "symptom_name": "Trẻ biếng ăn",
        "base_confidence": 0.6,
        "hints": (
            "trẻ biếng ăn",
            "bé biếng ăn",
            "quấy khóc",
            "khó ngủ",
        ),
    },
    {
        "symptom_id": "child_digestive",
        "symptom_name": "Trẻ rối loạn tiêu hóa",
        "base_confidence": 0.6,
        "hints": (
            "trẻ tiêu chảy",
            "bé đi ngoài",
            "trẻ nôn",
            "bé ói",
        ),
    },
)
